### ISSUE TITLE
error

### ISSUE THREAD

**Issue by makipsee** [olicooper/HAmerger#1]
i dont know if im doing something wrong but when i try to run it it stops and gives me this error on this line:

var oldMetaRows = oldDb.Select<StatisticMeta>();

Error: " System.Data.SQLite.SQLiteException: 'SQL logic error no such table: statistics_meta' "

**Comment by TheBigNeo** [comment]
@makipsee 

This happens when one of the DB files was not found.
Your db file names must match: https://github.com/olicooper/HAmerger/blob/e405b0195a9c12964fcf3a75adb5ac8d12a076db/HAmerger/Program.cs#L29

**Comment by makipsee** [comment]
@TheBigNeo 

I will check that out... I'm out of town right now. Thank you!

**Comment by olicooper** [comment]
Hey @TheBigNeo thanks for responding 👍
I think this could also happen if your database is corrupted or missing the `statistics_meta` table.
Also make sure you have both the `old.db` and `new.db` in the correct folder which is usually `HAMerger\bin\data\`... I have added a commit which will print the location where the program expects to find the database files.
